networks:
  db_net:
    driver: bridge
version: "3.7"
services:
  mongodb:
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: dpg
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: admin
    restart: always
    image: mongo:latest
    command: --quiet
  api:
    container_name: api
    ports:
      - 8080:8080
    build:
      context: ./api
      dockerfile: Dockerfile
  ui:
    container_name: ui
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./ui:/app
    stdin_open: true
    build:
      context: ./ui
      dockerfile: Dockerfile
  ciphertrust:
    image: thalesciphertrust/ciphertrust-data-protection-gateway:latest
    container_name: ciphertrust
    environment:
      - REG_TOKEN=rfxbPVMueQBXB6qJB20KNrgtxNwuribbAwk5PNcBL6MlrMy9g0djgjGkxcmzswyP
      - DESTINATION_URL=http://api:8080
      - DPG_PORT=9005
      - TLS_ENABLED=false
      - KMS=40.121.32.75
    ports:
      - 9005:9005
