networks:
  db_net:
    driver: bridge
version: "3.7"
services:
  mongodb:
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: dpg
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: admin
    restart: always
    image: mongo:latest
    command: --quiet
  api:
    container_name: api
    ports:
      - 8080:8080
    build:
      context: ./api
      dockerfile: Dockerfile
